### ISSUE TITLE
Singly Linked List implementation

### ISSUE THREAD

**Issue by dgraciac** [code-sherpas/kollections#12]
# First step

Search, read and understand information about lists, linked lists and singly linked lists, and how they are implemented.

# Second step

You have to share a code snippet in markdown with an interface proposal for this data structure. Below you can find an interface example of an hypothetical data structure:

```Kotlin
class MyDataStructure<E> {

    fun add(element: E) {
        TODO("Not yet implemented")
    }

    fun get(index: Int): E {
        TODO("Not yet implemented")
    }
}
```

# Third step

After @code-sherpas/kollections-maintainers approve your interface proposal, open a pull request with the data structure implementation and wait for comments.

## Minimum acceptance criteria

- The implementation must be well documented with proper [Javadoc](https://es.wikipedia.org/wiki/Javadoc) at Class and function levels.
- The implementation must be tested with automatic tests that cover all relevant cases and situations.
- The implementation must be [generic](https://kotlinlang.org/docs/generics.html).
- The implementation must have the expected time complexity according to the Computer Science. [Here you can find a very helpful cheatsheet](https://www.bigocheatsheet.com/).

# Related resources:

- https://www.youtube.com/watch?v=v4cd1O4zkGw&ab_channel=HackerRank
- https://www.youtube.com/watch?v=njTh_OwMljA&ab_channel=HackerRank
- https://en.wikipedia.org/wiki/List_(abstract_data_type)
- https://en.wikipedia.org/wiki/Linked_list#Singly_linked_list
- https://www.bigocheatsheet.com/

**Comment by ashikka** [comment]
@dgraciac Here is the interface proposal for this data structure.  Let me know if you require any changes. 
`kotlin
package main

class SinglyLinkedList<E> {

    // Insert element at the beginning of the list
    fun insertAtBeginning(element: E){
        TODO()
    }

    // Insert element after a specified node
    fun insertAfter(previousNode: E, element: E){
        TODO()
    }

    // Insert element at the end of the list
    fun insertAtEnd(element: E){
        TODO()
    }

    // Delete a node of a specified position
    fun deleteNode(position: E){
        TODO()
    }
}
`

**Comment by dgraciac** [comment]
Positions are integers
```
 fun deleteNode(position: Int){
        TODO()
    }
```

**Comment by dgraciac** [comment]
Passing a node is not needed:

```kotlin
    // Insert element after the first ocurrence of specified element
    fun insertAfter(element: E){
        TODO()
    }
```

**Comment by dgraciac** [comment]
After this interface changes, you can go with the implementation.

**Comment by dgraciac** [comment]
Consider add this operations in this PR. But up to you.

`fun get(index: Int): E`

`fun isEmpty(): Boolean`

`fun head(): E`

**Comment by ashikka** [comment]
Is this alright @dgraciac?

```Kotlin
package main
class SinglyLinkedList<E> {

    // Insert element at the beginning of the list
    fun insertAtBeginning(element:E) {
        TODO()
    }

    // Insert element after a specified node
    fun insertAfter(element:E) {
        TODO()
    }

    // Insert element at the end of the list
    fun insertAtEnd(element:E) {
        TODO()
    }

    // Delete a node of a specified position
    fun deleteNode(position:Integer) {
        TODO()
    }

    // Get element at a specified position
    fun get(index:Integer):E {
        TODO()
    }
    
    // Check is list is empty
    fun isEmpty(): Boolean{
        TODO()
    }

    // Find the element at the head of the list
    fun head():E{
        TODO()
    }
}
```

**Comment by dgraciac** [comment]
Please remove this operation because I am not sure about its value:

```
// Insert element after a specified node
    fun insertAfter(element:E) {
        TODO()
    }
```

You can start with the implementation.
