### ISSUE TITLE
Queue implementation

### ISSUE THREAD

**Issue by dgraciac** [code-sherpas/kollections#15]
# First step

Search, read and understand information about queues and how they are implemented.

# Second step

You have to share a code snippet in markdown with an interface proposal for this data structure. Below you can find an interface example of an hypothetical data structure:

```Kotlin
class MyDataStructure<E> {

    fun add(element: E) {
        TODO("Not yet implemented")
    }

    fun get(index: Int): E {
        TODO("Not yet implemented")
    }
}
```

# Third step

After @code-sherpas/kollections-maintainers approve your interface proposal, open a pull request with the data structure implementation and wait for comments.

## Minimum acceptance criteria

- The implementation must be well documented with proper [Javadoc](https://es.wikipedia.org/wiki/Javadoc) at Class and function levels.
- The implementation must be tested with automatic tests that cover all relevant cases and situations.
- The implementation must be [generic](https://kotlinlang.org/docs/generics.html).
- The implementation must have the expected time complexity according to the Computer Science. [Here you can find a very helpful cheatsheet](https://www.bigocheatsheet.com/).
- Compare efficiency using a dynamic array as underlying data structure vs using a linked list. Choose the most efficient.

# Related resources:

- https://www.youtube.com/watch?v=v4cd1O4zkGw&ab_channel=HackerRank
- https://www.youtube.com/watch?v=wjI1WNcIntg&ab_channel=HackerRank
- https://en.wikipedia.org/wiki/Queue_(abstract_data_type)
- https://www.bigocheatsheet.com/

**Comment by ashikka** [comment]
@dgraciac Here is the interface proposal for this data structure. Let me know if you require any changes.

```Kotlin 
class Queue<E> {

    // Add element to the tail of the queue
    fun enqueue(element: E) {
        TODO();
    }

    // Remove element from the head of the queue
    fun dequeue() {
        TODO();
    }

    // Find the size of the queue
    fun size() {
        TODO();
    }

    // Check if the queue is empty
    fun isEmpty() {
        TODO();
    }

    // Check if the queue is full
    fun isFull() {
        TODO();
    }
}
```

**Comment by dgraciac** [comment]
I would remove `isFull`.

**Comment by ashikka** [comment]
> I would remove `isFull`.

Alright! I will make the requested changes. Thank you!
