### ISSUE TITLE
Implement `isEmpty()` function for a Singly Linked List 

### ISSUE THREAD

**Issue by ashikka** [code-sherpas/kollections#24]
Taking reference from issue [#12](https://github.com/code-sherpas/kollections/issues/12), implement the `isEmpty()` function for a Singly Linked List. This function will check if the list is empty.

### First step
Search, read, and understand information about lists, linked lists, and singly-linked lists, and how they are implemented.

### Second step
Open a pull request with the data structure implementation, and wait for comments from @code-sherpas/kollections-maintainers.

### Minimum acceptance criteria
* The implementation must be well documented with proper Javadoc at Class and function levels.
* The implementation must be tested with automatic tests that cover all relevant cases and situations.
* The implementation must be generic.
* The implementation must have the expected time complexity according to Computer Science. [Here you can find a very helpful cheat sheet](https://www.bigocheatsheet.com/).

### Related resources:
* https://www.youtube.com/watch?v=v4cd1O4zkGw&ab_channel=HackerRank
* https://www.youtube.com/watch?v=njTh_OwMljA&ab_channel=HackerRank
* https://en.wikipedia.org/wiki/List_(abstract_data_type)
* https://en.wikipedia.org/wiki/Linked_list#Singly_linked_list
* https://www.bigocheatsheet.com/

**Comment by bhaveesarna** [comment]
@ashikka  I would like to work on this. Could you please assign it to me?

**Comment by ashikka** [comment]
> @ashikka I would like to work on this. Could you please assign it to me?

Sure!
