### ISSUE TITLE
Interface Implementation for Doubly Linked List

### ISSUE THREAD

**Issue by ashikka** [code-sherpas/kollections#48]
# First step

Search, read, and understand information about doubly linked lists and how they are implemented.

# Second step

You have to share a code snippet in markdown with an interface proposal for this data structure. Below you can find an interface example of a hypothetical data structure:

```Kotlin
class MyDataStructure<E> {

    fun add(element: E) {
        TODO("Not yet implemented")
    }

    fun get(index: Int): E {
        TODO("Not yet implemented")
    }
}
```

# Third step

After @code-sherpas/kollections-maintainers approve your interface proposal, open a pull request with the data structure implementation, and wait for comments.

## Minimum acceptance criteria

- The implementation must be well documented with proper [Javadoc](https://es.wikipedia.org/wiki/Javadoc) at Class and function levels.
- The implementation must be tested with automatic tests that cover all relevant cases and situations.
- The implementation must be [generic](https://kotlinlang.org/docs/generics.html).
- The implementation must have the expected time complexity according to Computer Science. [Here you can find a very helpful cheat sheet](https://www.bigocheatsheet.com/).

**Comment by bhaveesarna** [comment]
Hey @ashikka could you please assign this to me?

**Comment by bhaveesarna** [comment]
Does this work @ashikka ?

```kotlin
package main

class DoublyLinkedList<E> {

    //Return element at the head of the Doubly Linked List
    fun head(): E{
        TODO()
    }

    //Return element at the tail of the Doubly Linked List
    fun tail(): E{
        TODO()
    }

    //Insert element at the beginning of the Doubly Linked List
    fun insertAtBeginning(element:E){
        TODO()
    }

    //Insert element at the end of the Doubly Linked List
    fun insertAtEnd(element:E){
        TODO()
    }

    //Insert element at specified index of the Doubly Linked List
    fun insertAtIndex(index:Integer){
        TODO()
    }
    
    //Return element at specified index of the Doubly Linked List
    fun get(index:Integer): E{
        TODO()
    }

    //Delete the node at specified index of the Doubly Linked List
    fun deleteNode(index:Integer){
        TODO()
    }

    //Delete the node at the head of the Doubly Linked List
    fun deleteFirst(){
        TODO()
    }

    //Delete the node at the tail of the Doubly Linked List
    fun deleteLast(){
        TODO()
    }
}
```

**Comment by ashikka** [comment]
Looks good to me @bhaveesarna! Could you request a review from @dgraciac also?

**Comment by bhaveesarna** [comment]
@dgraciac could you please review the interface proposal?

**Comment by dgraciac** [comment]
@bhaveesarna I would remove

**Comment by dgraciac** [comment]
@bhaveesarna I would remove

**Comment by dgraciac** [comment]
@bhaveesarna I would remove
```
    //Return element at the tail of the Doubly Linked List
    fun tail(): E{
        TODO()
    }
```

because it is a bit more complex than other operations. We can include this operation in future issues.

Other operations are fine IMO. Go ahead.

**Comment by ashikka** [comment]
Good work @bhaveesarna :rocket:! I"ll be closing this issue now.
